# Generated by Django 5.0.4 on 2024-05-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=128, unique=True)),
                ('subcategory_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.certificatecategory', to_field='category')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=128, unique=True)),
                ('training_name', models.CharField(max_length=256)),
                ('training_type', models.CharField(choices=[('CER', 'certification'), ('TR', 'training'), ('EX', 'exam')], max_length=13)),
                ('date', models.DateField()),
                ('certificate_file', models.FileField(upload_to='certificates')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificate.certificatecategory', to_field='category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='certificate.certificatesubcategory', to_field='subcategory')),
            ],
        ),
    ]
