insert into self_assessment_hardware (product)
values ('ProLiant & Apollo'),
('BladeSystem'),
('Synergy'),
('SimpliVity'),
('B-series SAN'),
('Aruba Switches'),
('Aruba Routers'),
('FlexNetwork Switches'),
('FlexFabric Switches'),
('OfficeConnect Switches'),
('Aruba Mobility Controllers'),
('Aruba Hotspots'),
('MSA'),
('Nimble'),
('3PAR/Primera'),
('Autoloader & MSL'),
('StoreOnce'),
('StoreEasy');

insert into self_assessment_taskhw (task)
values ('art Replacement'),
        ('Rack Mounting'),
        ('Cabling'),
        ('Startup'),
        ('Basic Configuration'),
        ('Log Collection'),
        ('Log Parsing'),
        ('Diagnostics'),
        ('Configuration Design'),
        ('Firmware Update'),
        ('Performance Metrics Setup'),
        ('Performance Collection');

INSERT INTO self_assessment_software (product) VALUES
('Microsoft Windows Server'),
('Red Hat Enterprise Linux'),
('SUSE Linux Enterprise Server'),
('VMware vSphere'),
('Microsoft Hyper-V'),
('Red Hat Enterprise Virtualization'),
('SUSE Xen Virtualization'),
('SUSE KVM Virtualization'),
('Docker'),
('Kubernetes'),
('Microsoft Failover Cluster'),
('Red Hat High Availability Add-On'),
('SUSE Linux Enterprise High Availability Extension'),
('Microfocus Data Protector'),
('Veeam Backup & Replication'),
('DellEMC NetWorker'),
('Veritas NetBackup'),
('Veritas Backup Exec'),
('Microsoft SQL Server'),
('Oracle Database'),
('PostgreSQL'),
('MySQL/MariaDB');

INSERT INTO self_assessment_tasksw (task) VALUES
('Installation'),
('Basic Configuration'),
('Fine Tuning'),
('Performance Collection'),
('Performance Tuning');

INSERT INTO self_assessment_processes (process) VALUES
('PRINCE2 Project Management'),
('PMI Project Management'),
('TOGAF Enterprise Architecture'),
('Technical Writing'),
('Negotiations with Customer'),
('Correspondence with Customer'),
('Performance Analysis (Statistics)'),
('Solution High Level Design'),
('Solution Low Level Design'),
('Customer Presentations'),
('Testing and Acceptance Planning'),
('Technical Training Delivery'),
('Technical Training Development'),
('ITIL/ITSM');