services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: false
        bind:
          create_host_path: true
        volume:
          nocopy: false
        consistency: cached
      - type: volume
        source: sqlite_data
        target: /app/db
      - type: volume
        source: media_volume
        target: /app/files
      - type: volume
        source: static_volume
        target: /app/staticfiles
    entrypoint: ["sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    environment:
      - DJANGO_SETTINGS_MODULE=ska.settings

volumes:
  sqlite_data:
  media_volume:
  static_volume: