services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - media_volume:/app/files
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=ska.settings
      - SECRET_KEY=your-secret-key-here

volumes:
  sqlite_data:
  media_volume: