services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: sqlite_data
        target: /app/db
      - type: volume
        source: media_volume
        target: /app/files
      - type: volume
        source: static_volume
        target: /app/staticfiles
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      - DJANGO_SETTINGS_MODULE=ska.settings
    command: ["tail", "-f", "/dev/null"]

volumes:
  sqlite_data:
  media_volume:
  static_volume: