services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - media_volume:/app/files
      - static_volume:/app/staticfiles
    entrypoint: ["sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    environment:
      - DJANGO_SETTINGS_MODULE=ska.settings

volumes:
  sqlite_data:
  media_volume:
  static_volume: