services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - media_volume:/app/files
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=ska.settings
      - SECRET_KEY=your-secret-key-here
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  sqlite_data:
  media_volume:
  static_volume: