# Generated by Django 5.0.4 on 2024-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='employee_name',
            field=models.CharField(max_length=128),
        ),
    ]
