# Generated by Django 5.1rc1 on 2024-07-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_certificate_date'),
        ('self_assessment', '0004_employees_is_supervisor_employees_subordinate_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees'),
        ),
    ]
