# Generated by Django 5.1rc1 on 2024-07-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_remove_certificate_employee_name_and_more'),
        ('self_assessment', '0004_employees_is_supervisor_employees_subordinate_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees'),
        ),
    ]
