# Generated by Django 5.0.4 on 2024-05-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillshw',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.hardware', to_field='product'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.taskhw', to_field='task'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.processes', to_field='process'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.software', to_field='product'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.tasksw', to_field='task'),
        ),
    ]
