# Generated by Django 5.0.4 on 2024-05-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0002_alter_skillshw_product_alter_skillshw_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillshw',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level'),
        ),
    ]
