# Generated by Django 5.1a1 on 2024-07-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0003_alter_skillshw_level_alter_skillssw_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='subordinate_of',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.employees'),
        ),
    ]
