# Generated by Django 5.1.3 on 2024-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0006_alter_department_options_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('supervisor', 'Руководитель'), ('admin', 'Администратор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
