# Generated by Django 5.0.4 on 2024-05-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(unique=True)),
                ('level', models.TextField(unique=True)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKillsPr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.processes')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsHW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.hardware')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.taskhw')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.software')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.tasksw')),
            ],
        ),
    ]
