# Generated by Django 5.1.3 on 2024-11-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0005_department_employees_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['product'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['weight'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='processes',
            options={'ordering': ['process'], 'verbose_name': 'Процесс', 'verbose_name_plural': 'Процессы'},
        ),
        migrations.AlterModelOptions(
            name='skillshw',
            options={'ordering': ['-time'], 'verbose_name': 'Навык по оборудованию', 'verbose_name_plural': 'Навыки по оборудованию'},
        ),
        migrations.AlterModelOptions(
            name='skillspr',
            options={'ordering': ['-time'], 'verbose_name': 'Навык по процессам', 'verbose_name_plural': 'Навыки по процессам'},
        ),
        migrations.AlterModelOptions(
            name='skillssw',
            options={'ordering': ['-time'], 'verbose_name': 'Навык по ПО', 'verbose_name_plural': 'Навыки по ПО'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['product'], 'verbose_name': 'ПО', 'verbose_name_plural': 'ПО'},
        ),
        migrations.AlterModelOptions(
            name='taskhw',
            options={'ordering': ['task'], 'verbose_name': 'Задача по оборудованию', 'verbose_name_plural': 'Задачи по оборудованию'},
        ),
        migrations.AlterModelOptions(
            name='tasksw',
            options={'ordering': ['task'], 'verbose_name': 'Задача по ПО', 'verbose_name_plural': 'Задачи по ПО'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Является руководителем'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='subordinate_of',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.employees', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='product',
            field=models.TextField(unique=True, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='description',
            field=models.TextField(unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level',
            field=models.TextField(unique=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='weight',
            field=models.IntegerField(unique=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='process',
            field=models.TextField(unique=True, verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.hardware', to_field='product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.taskhw', to_field='task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='skillshw',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время оценки'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.processes', to_field='process', verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='skillspr',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время оценки'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_assessment.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.levels', to_field='level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.software', to_field='product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='self_assessment.tasksw', to_field='task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='skillssw',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время оценки'),
        ),
        migrations.AlterField(
            model_name='software',
            name='product',
            field=models.TextField(unique=True, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='taskhw',
            name='task',
            field=models.TextField(unique=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='tasksw',
            name='task',
            field=models.TextField(unique=True, verbose_name='Задача'),
        ),
    ]
